### ISSUE TITLE
crash on stack creation when library is used in create-react-app env

### ISSUE THREAD

**Issue by BL-EVER** [dstack-js/dstack#88]
**Describe the bug**
When the library is used in a React application according to the custom relay in the getting started docs (https://dstack.dev/docs/intro) The following error in pubsub-adapter.js is thrown: Uncaught (in promise) TypeError: PubsubRouter is not a constructor

**To Reproduce**
1. Ad the library in a React application
2. Run it
3. Visit the console in the Developer tools of Chrome
4. See the error

**Reproduce Code Example or Repository**
```javascript
React.useEffect(()=>{
        async function fetchData() {
            const stack = await Stack.create({
                namespace: 'namespace',
                relay: 'https://relay.dstack.dev:443/graphql'
            }, wrtc);
            console.log('My Peer ID is:', stack.id);
        }
        fetchData();
    },[])
```

**Expected behavior**
The library to connect to the relay and provide the id

**Screenshots or logs**
![image](https://user-images.githubusercontent.com/46745853/160399462-6b7c7e4a-6560-4329-aed0-cb4fbb867c62.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Environment: Chrome, nodejs, React, WSL2
 - Environment Version latest

**Additional context**

**Comment by 0x77dev** [comment]
Hey @BL-EVER, can you please provide a little bit more information on your setup?

1. Bunder? (Webpack/Parcel/etc)
2. Browser Version?
3. Any additional info on your react project configuration? 
4. Installed DStack packages and their versions?

**Comment by 0x77dev** [comment]
Confirmed, will look into this

P.S. You don’t need to use custom wrtc (`@dstackjs/wrtc` module) in a browser environment

**Comment by 0x77dev** [comment]
As a workaround, you can initiate your react project using create-react-app alternatives, [explorer](https://explorer.dstack.dev) uses a bare webpack setup.

Also when configuring a project with webpack or similar alternatives you need to provide some of the Node.js polyfills for IPFS to work inside a browser, you can refer to [js-ipfs example webpack configuration](https://github.com/ipfs-examples/js-ipfs-examples/tree/master/examples/browser-webpack) or [similar browser js-ipfs examples](https://github.com/ipfs-examples/js-ipfs-examples/tree/master/examples)
